[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[[deploy.volumes]]
mountPath = "/data"
name = "telegram-bot-storage"
